---
services: docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker build -t docker-ansible .
  - docker run --name test-container -v /sys/fs/cgroup:/sys/fs/cgroup:ro -d --privileged docker-ansible
  - docker exec --tty test-container env TERM=xterm ansible --version
